fix: limit job name width and details
taskless/taskless pull request #13
Opened 2022-10-03 21:13 UTC by TAKANOME-DEV

- Add max width of `300px` for `DEFAULT_CELL` width and `text-ellipsis` to the job name

| ![after_jobs](https://user-images.githubusercontent.com/79809121/193682686-4cb9d1ef-b2cc-43cd-9c74-16ef6d5c178e.png) 	| ![before_jobs](https://user-images.githubusercontent.com/79809121/193682453-d4ec7997-7577-45f2-be4d-8986b83e10c6.png) 	|
|----------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------------	|
|                                                                                                                      	|                                                                                                                       	|

- Add `overflow-hidden` to the logs table container and `max-w-5xl` for the job details

|![logs_before](https://user-images.githubusercontent.com/79809121/193683455-30476fec-2eca-4411-8d8a-1726053304d1.png)	| ![logs_after](https://user-images.githubusercontent.com/79809121/193683515-3e8d35ff-04ae-4f7e-a9d8-78a4127a9007.png)	|
|----------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------------	|
|                                                                                                                      	|                                                                                                                       	|

Fixes #4

2022-10-04 21:51 UTC, jakobo requested changes
Just a few comments RE formatting and supporting mobile screen sizes. Thank you for putting this together! :heart:

2022-10-04 21:51 UTC, jakobo commented on packages/ui/src/components/DataTable.tsx
> +const DEFAULT_CELL = "py-4 px-3 text-sm text-gray-500 max-w-[300px]";
May want to consider mobile screen sizes, plus either a width of 72 or 80 (https://tailwindcss.com/docs/width): `max-w-full md:max-w-72`. This avoids having too many custom values that need checking in a design change.

2022-10-04 21:51 UTC, jakobo commented on packages/dev/src/pages/index.tsx
> +          className="flex flex-row items-center flex-shrink-0 gap-3 px-3 py-2 text-white transition rounded-md bg-primary-700 hover:bg-primary-500"
Is there a plugin / code formatter that's updating the order of classes? I see [there is an official plugin for prettier](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier), but we don't have that added yet in our own package.json.

Specifically asking because the reordering does make it difficult to tell which changes are specific to this PR vs formatting improvements.

2022-10-04 22:20 UTC, TAKANOME-DEV commented on packages/dev/src/pages/index.tsx
> +          className="flex flex-row items-center flex-shrink-0 gap-3 px-3 py-2 text-white transition rounded-md bg-primary-700 hover:bg-primary-500"
Sorry about that :sweat: it's an extension, I will revert it :+1:

2022-10-04 22:20 UTC, TAKANOME-DEV commented on packages/ui/src/components/DataTable.tsx
> +const DEFAULT_CELL = "py-4 px-3 text-sm text-gray-500 max-w-[300px]";
sure

2022-10-04 23:06 UTC, TAKANOME-DEV commented on packages/ui/src/components/DataTable.tsx
> +const DEFAULT_CELL = "py-4 px-3 text-sm text-gray-500 max-w-[300px]";
it does not work with `max-w-72 or max-w-80`, and for the logs when the details are opened, it overflows.
Will take more time to fix it :v:

2022-10-04 23:53 UTC, jakobo commented on packages/dev/src/pages/index.tsx
> +          className="flex flex-row items-center flex-shrink-0 gap-3 px-3 py-2 text-white transition rounded-md bg-primary-700 hover:bg-primary-500"
No worries! I actually think this is a good thing. Let me put the plugin in place across the board, as it will make diffing the changes much easier.

2022-10-10 16:47 UTC, TAKANOME-DEV commented
Added a `div` container to eliminate horizontal scrolling :arrow_down: 

[taskless.webm](https://user-images.githubusercontent.com/79809121/194915505-db7b25d4-2b99-4628-b272-fb35c39d129d.webm)

2022-10-10 21:50 UTC, jakobo reviewed
Looks good. Only one small question in the review RE a console.log statement. 🚀

2022-10-10 21:50 UTC, jakobo commented on packages/dev/src/pages/logs.tsx
> +              console.log({ payload });
Do we need this console.log statement?

2022-10-10 22:03 UTC, TAKANOME-DEV commented on packages/dev/src/pages/logs.tsx
> +              console.log({ payload });
My bad, just have a habit to throw console.log everywhere :sweat_smile: , gonna remove it

2022-10-11 18:30 UTC, jakobo approved these changes

2022-10-11 18:31 UTC, merged

2022-10-11 18:31 UTC, jakobo commented
@all-contributors please add @TAKANOME-DEV for code ❤️