ci: Add basic CI workflow
taskless/taskless pull request #19
Opened 2023-06-06 17:32 UTC by segiddins

2023-06-08 20:24 UTC, jakobo requested changes
Review format follows Netlify's [Feedback Ladders](https://www.netlify.com/blog/2020/03/05/feedback-ladders-how-we-encode-code-reviews-at-netlify/) to help clarify severity in the comments.

<hr />

Nothing in this looks to be a blocker at first glance, but it is worth discussing the nx dependency. That's probably the biggest change, and one that (currently) can also be solved with `pnpm run` which has an implicit topological sort and the ability to ignore missing commands.

It's not a perfect system, I just want to be cautious about adding complexity. These aren't parallelized like nx promises to be at the task-runner level, but nx itself may also be overkill for this stage.

```
# approximate based on PR
pnpm run -r --if-present codegen
pnpm run -r --if-present lint
pnpm run -r --if-present eslint
pnpm run -r --if-present typecheck
pnpm run -r --if-present tsup
pnpm run -r --if-present build
pnpm run -r --if-present test
```

2023-06-08 20:24 UTC, jakobo commented on docs-site/markdoc/components/Tabs.tsx
> +  children: React.ReactNode;
[pebble] Prefer the generic format `React.PropsWithChildren<Prop>` over `children: React.ReactNode`

2023-06-08 20:24 UTC, jakobo commented on docs-site/markdoc/components/Tabs.tsx
> +  children: React.ReactNode;
[pebble] Prefer the generic format `React.PropsWithChildren<Prop>` over `children: React.ReactNode`

2023-06-08 20:24 UTC, jakobo commented on docs-site/markdoc/schema.ts
> +export const markdocComponents = {
[sand] Is there a good case for removing the type restriction on `markdocComponents`?

2023-06-08 20:24 UTC, jakobo commented on nx.json
> +{
[pebble] The PR comments should talk about the decision to use nx & alternatives considered. No objections to using it for CI, but it is one more piece of a tech a contributor will need to be aware of.

2023-06-13 15:11 UTC, segiddins commented on docs-site/.eslintrc.js
> +  extends: ["../.eslintrc.cjs", "plugin:@next/next/recommended"],
`pnpm eslint` doesn't seem to actually lint anything? I needed to add the child ones to get the nextjs plugin in, I think

2023-06-13 15:30 UTC, segiddins commented on docs-site/.eslintrc.js
> +  extends: ["../.eslintrc.cjs", "plugin:@next/next/recommended"],
```
❯ pnpm eslint .

> @taskless/root@3.6.2 eslint /Users/segiddins/Development/github.com/taskless/taskless
> eslint "."

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.9.0

YOUR TYPESCRIPT VERSION: 5.1.3

Please only submit bug reports when using the officially supported version.

=============
DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.
Pages directory cannot be found at /Users/segiddins/Development/github.com/taskless/taskless/pages or /Users/segiddins/Development/github.com/taskless/taskless/src/pages. If using a custom path, please configure with the `no-html-link-for-pages` rule in your eslint config file.
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.0.0

YOUR TYPESCRIPT VERSION: 5.1.3

Please only submit bug reports when using the officially supported version.

=============

/Users/segiddins/Development/github.com/taskless/taskless/verify/esm/esm.verify.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

✖ 1 problem (1 error, 0 warnings)

 ELIFECYCLE  Command failed with exit code 1.
 ```

2023-06-13 20:41 UTC, jakobo approved these changes

2023-06-13 20:44 UTC, jakobo commented
Thanks! Everything looks great.

@all-contributors please add @segiddins for code, infra, test

2023-06-13 20:47 UTC, merged